services:
  fleetapp.api:
    build:
      context: .
      dockerfile: src/FleetApp.Api/Dockerfile
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=http://+:8080
    ports:
      - "8080:8080"
